// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.advert.controller.resp;

import java.lang.Object;

privileged aspect RuanlieResponseData_Roo_JavaBean {
    
    public Object RuanlieResponseData.getResult() {
        return this.result;
    }
    
    public void RuanlieResponseData.setResult(Object result) {
        this.result = result;
    }
    
}
